insert into "Gifts" (name, url) values ('Набор для маникюра Orly Gel FX Starter Kit','https://goo.gl/Wv6kdu')
insert into "Gifts" (name, url) values ('Тарелка «Серый кит»','https://goo.gl/NkMgqe')
insert into "Gifts" (name, url) values ('Украшения Pandora','https://goo.gl/KZwYZZ')
insert into "Gifts" (name, url) values ('Дорожная подушка','https://goo.gl/bJVH9w')
insert into "Gifts" (name, url) values ('Дорожная подушка','https://goo.gl/spZAqL')
insert into "Gifts" (name, url) values ('Дорожная подушка','https://goo.gl/2XM1bR')
insert into "Gifts" (name, url) values ('Женские носки','https://goo.gl/huPZGH')
insert into "Gifts" (name, url) values ('Ароматические палочки','https://goo.gl/nHjG8V')
insert into "Gifts" (name, url) values ('Набор для мехенди','https://goo.gl/TGNQje')
insert into "Gifts" (name, url) values ('Билеты на концерты','https://goo.gl/59s5wc')
insert into "Gifts" (name, url) values ('Пемза','https://goo.gl/ytDuuz')
insert into "Gifts" (name, url) values ('Гамак','https://goo.gl/osq8gK')
insert into "Gifts" (name, url) values ('Спортивное бра','https://goo.gl/t2v2cL')
insert into "Gifts" (name, url) values ('Набор «ЗОЖ»','https://goo.gl/PLzRrn')
insert into "Gifts" (name, url) values ('Полезные Бады','https://goo.gl/KjBhn1')
insert into "Gifts" (name, url) values ('Карта мира «TrueMap»','https://goo.gl/c77AWP')
insert into "Gifts" (name, url) values ('Игра Sims 4','https://goo.gl/511L4K')
insert into "Gifts" (name, url) values ('Вспышка селфи для IPhone','https://goo.gl/skAnwH')
insert into "Gifts" (name, url) values ('Лосьон 2 в 1: с фруктовыми кислотами Lotion Post-Epil','https://goo.gl/YJvDrw')
insert into "Gifts" (name, url) values ('Фартук','https://goo.gl/kN6o4m')
insert into "Gifts" (name, url) values ('Экочеловек «Мечтатель»','https://goo.gl/fUtR7q')
insert into "Gifts" (name, url) values ('Глобус звездного неба','https://goo.gl/G7jTW6')
insert into "Gifts" (name, url) values ('Jelly Belly Ассорти','https://goo.gl/Mc7sks')
insert into "Gifts" (name, url) values ('Подвеска малая Единорог','https://goo.gl/294GJi')
insert into "Gifts" (name, url) values ('Полёт в аэротрубе','https://goo.gl/4WmWwc')
insert into "Gifts" (name, url) values ('Ночная маска Panda\'s Dream White Sleeping Pack','https://goo.gl/hHXjcG')
insert into "Gifts" (name, url) values ('Корзина для белья','https://goo.gl/Q4x39Z')
insert into "Gifts" (name, url) values ('Ключница МЖ','https://goo.gl/VByDuu')
insert into "Gifts" (name, url) values ('Сапожки-грелки','https://goo.gl/Fx3zC2')
insert into "Gifts" (name, url) values ('Полка для ванны','https://goo.gl/T36Jmy')
insert into "Gifts" (name, url) values ('Волейбольный мяч','https://goo.gl/XQ3zMB')
insert into "Gifts" (name, url) values ('Корзина для белья','https://goo.gl/D8KD1Q')
insert into "Gifts" (name, url) values ('Духи «Книжный переплет»','https://goo.gl/XganHd')
insert into "Gifts" (name, url) values ('Мармелад из вина','https://goo.gl/t8Hr5o')
insert into "Gifts" (name, url) values ('Конфитюр из пива','https://goo.gl/kTwrST')
insert into "Gifts" (name, url) values ('Звезда с неба','https://goo.gl/zw1hJG')
insert into "Gifts" (name, url) values ('Духи «Секс на пляже»','https://goo.gl/9iZ7oN')
insert into "Gifts" (name, url) values ('Подарочный набор для выращивания «Анютины глазки»','https://goo.gl/v33LXa')
insert into "Gifts" (name, url) values ('Подарочный сертификат на курсы фотографии','https://goo.gl/Pf6iT6')
insert into "Gifts" (name, url) values ('Кружка Ахматова','https://goo.gl/4gXKb2')
insert into "Gifts" (name, url) values ('Подарочный сертификат на фотосессию','https://goo.gl/5SkG9g')
insert into "Gifts" (name, url) values ('Мягкая игрушка «Ты лучше всех»','https://goo.gl/oEn23d')
insert into "Gifts" (name, url) values ('Значок металлический Маяковский','https://goo.gl/3q8H2e')
insert into "Gifts" (name, url) values ('Конная прогулка','https://goo.gl/bqgo2R')
insert into "Gifts" (name, url) values ('Хна для мехенди «Кавери»','https://goo.gl/QXExUR')
insert into "Gifts" (name, url) values ('Убегающий будильник','https://goo.gl/6J34JM')
insert into "Gifts" (name, url) values ('Настольная игра «Манчкин»','https://goo.gl/mdQqQK')
insert into "Gifts" (name, url) values ('Кигуруми','https://goo.gl/F8tVjk')
insert into "Gifts" (name, url) values ('Подарочная карта в Спортмастер','https://goo.gl/Bi8MWH')
insert into "Gifts" (name, url) values ('Кружка-термос с Гари Поттером','https://goo.gl/DhedQy')
insert into "Gifts" (name, url) values ('Духи «Пончик»','https://goo.gl/xT8qYn')
insert into "Gifts" (name, url) values ('Пазлы','https://goo.gl/Q6gVpz')
