insert into "Gifts" (name, url) values ('Набор для маникюра Orly Gel FX Starter Kit','https://pudra.ru/orly/brush-nail-artist-dotter-duo-44148.html')
insert into "Gifts" (name, url) values ('Тарелка «Серый кит»','https://vsedrugoeshop.ru/catalog/posuda/tarelka_seryy_kit/')
insert into "Gifts" (name, url) values ('Украшения Pandora','http://www.pandora.net/ru-ru/campaigns/perfectmatch/by/filter/mostpopular')
insert into "Gifts" (name, url) values ('Дорожная подушка','https://modi.ru/catalog/goods/dorozhnaya-podushka-1/')
insert into "Gifts" (name, url) values ('Дорожная подушка','https://modi.ru/catalog/goods/dorozhnaya-podushka/')
insert into "Gifts" (name, url) values ('Дорожная подушка','https://modi.ru/catalog/goods/podushka-dlya-puteshestviy-1/')
insert into "Gifts" (name, url) values ('Женские носки','https://modi.ru/catalog/goods/noski-zhenskie-13/')
insert into "Gifts" (name, url) values ('Ароматические палочки','https://eco-list.ru/lavanda-aromaticheskie-palochki')
insert into "Gifts" (name, url) values ('Набор для мехенди','https://indiaretail.ru/index.php?route=product/category&path=215_177_181')
insert into "Gifts" (name, url) values ('Билеты на концерты','https://www.afisha.ru/samara/concerts/')
insert into "Gifts" (name, url) values ('Пемза','https://modi.ru/catalog/goods/pemza-1/')
insert into "Gifts" (name, url) values ('Гамак','https://agmashop.ru/products/gamak-kreslo-s-podlokotnikami-hm-013')
insert into "Gifts" (name, url) values ('Спортивное бра','https://www.sportmaster.ru/product/10182407/')
insert into "Gifts" (name, url) values ('Набор «ЗОЖ»','https://vsedrugoeshop.ru/catalog/eda_napitki_sladosti/nabor_zozh/')
insert into "Gifts" (name, url) values ('Полезные Бады','https://indiaretail.ru/index.php?route=product/category&path=215_173_209')
insert into "Gifts" (name, url) values ('Карта мира «TrueMap»','https://vsedrugoeshop.ru/catalog/karty/karta_mira_truemap/')
insert into "Gifts" (name, url) values ('Игра Sims 4','https://www.dns-shop.ru/product/826debfb08003120/igra-dla-pk-the-sims-4/')
insert into "Gifts" (name, url) values ('Вспышка селфи для IPhone','https://www.banggood.com/ru/Portable-LED-Ring-Flash-Light-Camera-Photography-Adapter-For-IPhone-Mobile-Phone-p-1045552.html')
insert into "Gifts" (name, url) values ('Лосьон 2 в 1: с фруктовыми кислотами Lotion Post-Epil','https://pudra.ru/aravia-professional/krem-s-ana-kislotami-professional-aha-cream-73661.html')
insert into "Gifts" (name, url) values ('Фартук','https://vsedrugoeshop.ru/catalog/kukhonnye_prinadlezhnosti/fartuk_squirrel/')
insert into "Gifts" (name, url) values ('Экочеловек «Мечтатель»','https://vsedrugoeshop.ru/catalog/dlya_rasteniy/ekochelovek_mechtatel_/')
insert into "Gifts" (name, url) values ('Глобус звездного неба','https://vsedrugoeshop.ru/catalog/oformlenie_interera/svetyashchiysya_globus_zvezdnogo_neba_star_light_globe/')
insert into "Gifts" (name, url) values ('Jelly Belly Ассорти','https://vsedrugoeshop.ru/catalog/sladosti/jelly_belly_assorti_bertie_botts_54_gr/')
insert into "Gifts" (name, url) values ('Подвеска малая Единорог','https://vsedrugoeshop.ru/catalog/ukrasheniya_i_podstavki_dlya_ukrasheniy/podveska_malaya_edinorog/')
insert into "Gifts" (name, url) values ('Полёт в аэротрубе','https://fifty-gifty.ru/catalog/polety/svobodnyy-polet-v-aerotrube/')
insert into "Gifts" (name, url) values ('Ночная маска Panda's Dream White Sleeping Pack','https://pudra.ru/tony-moly/nochnaya-maska-pandas-dream-white-sleeping-pack-30181.html?collection_product_id=30180')
insert into "Gifts" (name, url) values ('Корзина для белья','https://modi.ru/catalog/goods/korobka-dlya-khraneniya-4/')
insert into "Gifts" (name, url) values ('Ключница МЖ','https://vsedrugoeshop.ru/catalog/oformlenie_interera/klyuchnitsa_mzh_dub_buk/')
insert into "Gifts" (name, url) values ('Сапожки-грелки','https://vsedrugoeshop.ru/catalog/tapochki/sapozhki_grelki_bezhevye_35_40/')
insert into "Gifts" (name, url) values ('Полка для ванны','https://vsedrugoeshop.ru/catalog/vannaya/polka_dlya_vanny_aquala/')
insert into "Gifts" (name, url) values ('Волейбольный мяч','https://www.sportmaster.ru/product/1648977/')
insert into "Gifts" (name, url) values ('Корзина для белья','https://modi.ru/catalog/goods/korzina-dlya-belya/')
insert into "Gifts" (name, url) values ('Духи «Книжный переплет»','https://vsedrugoeshop.ru/catalog/kosmetika/dukhi_knizhnyy_pereplet_30_ml/')
insert into "Gifts" (name, url) values ('Мармелад из вина','https://vsedrugoeshop.ru/catalog/eda_napitki_sladosti/marmelad_iz_vina_170_ml/')
insert into "Gifts" (name, url) values ('Конфитюр из пива','https://vsedrugoeshop.ru/catalog/eda_napitki_sladosti/konfityur_iz_piva_106_ml/')
insert into "Gifts" (name, url) values ('Звезда с неба','https://roskocmoc.ru/order.php')
insert into "Gifts" (name, url) values ('Духи «Секс на пляже»','https://vsedrugoeshop.ru/catalog/kosmetika/dukhi_seks_na_plyazhe_30_ml/')
insert into "Gifts" (name, url) values ('Подарочный набор для выращивания «Анютины глазки»','https://vsedrugoeshop.ru/catalog/dlya_rasteniy/podarochnyy_nabor_dlya_vyrashchivaniya_anyutiny_glazki_ya_tebya_lyublyu/')
insert into "Gifts" (name, url) values ('Подарочный сертификат на курсы фотографии','https://photoplay.ru/gift.html')
insert into "Gifts" (name, url) values ('Кружка Ахматова','https://vsedrugoeshop.ru/catalog/kruzhki/kruzhka_akhmatova/')
insert into "Gifts" (name, url) values ('Подарочный сертификат на фотосессию','http://www.maximbubnov.com/giftcertificates')
insert into "Gifts" (name, url) values ('Мягкая игрушка «Ты лучше всех»','https://vsedrugoeshop.ru/catalog/igrushki/igrushka_myagkaya_ty_luchshe_vsekh/')
insert into "Gifts" (name, url) values ('Значок металлический Маяковский','https://vsedrugoeshop.ru/catalog/znachki/znachok_metallicheskiy_mayakovskiy/')
insert into "Gifts" (name, url) values ('Конная прогулка','http://www.ps-box.ru/sertifikat/konnaya-progulka')
insert into "Gifts" (name, url) values ('Хна для мехенди «Кавери»','https://indiaretail.ru/index.php?route=product/product&path=215_177_181&product_id=288')
insert into "Gifts" (name, url) values ('Убегающий будильник','https://mrgeek.ru/product/begajushij-budilnik')
insert into "Gifts" (name, url) values ('Настольная игра «Манчкин»','https://vsedrugoeshop.ru/catalog/nastolnye_igry/nastolnaya_igra_manchkin/')
insert into "Gifts" (name, url) values ('Кигуруми','https://diko-obraz.ru/all_kigurumi')
insert into "Gifts" (name, url) values ('Подарочная карта в Спортмастер','https://www.sportmaster.ru/egc/checkout.do?price=2000')
insert into "Gifts" (name, url) values ('Кружка-термос с Гари Поттером','http://www.asos.com/ru/paladone/harry-potter-hogwarts/prd/9418376?clr=%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8&SearchQuery=&cid=16095&gridcolumn=1&gridrow=12&gridsize=4&pge=2&pgesize=72&totalstyles=662')
insert into "Gifts" (name, url) values ('Духи «Пончик»','https://vsedrugoeshop.ru/catalog/kosmetika/dukhi_ponchik_30_ml/')
insert into "Gifts" (name, url) values ('Пазлы','https://1001puzzle.ru/')
