insert into "Gifts" (name, url) values ('Приставка Sega Magistr Drive 2 + 160 игр','https://goo.gl/1Pgt2y');
insert into "Gifts" (name, url) values ('Набор «4 варенья»','https://goo.gl/9VRAQj');
insert into "Gifts" (name, url) values ('Настенная фоторамка','https://goo.gl/s1wqBj');
insert into "Gifts" (name, url) values ('Карта мира TrueMap','https://goo.gl/oHgyrV');
insert into "Gifts" (name, url) values ('Меловая доска на холодильник «Сердце»','https://goo.gl/YMKomq');
insert into "Gifts" (name, url) values ('Фотоаппарат INSTAX Mini White','https://goo.gl/VUxhjt');
insert into "Gifts" (name, url) values ('Настольная игра «Мафия. Большой город»','https://goo.gl/kQom6R');
insert into "Gifts" (name, url) values ('Светящийся глобус звездного неба','https://goo.gl/hGxamL');
insert into "Gifts" (name, url) values ('Кубик Рубика 5x5','https://goo.gl/YKDE7z');
insert into "Gifts" (name, url) values ('Термокружка Grano «Винни Пух»','https://goo.gl/R3N4sC');
insert into "Gifts" (name, url) values ('Набор ЗОЖ','https://goo.gl/PXFVKm');
insert into "Gifts" (name, url) values ('3D-пазл «Цветок»','https://goo.gl/zyEEpM');
insert into "Gifts" (name, url) values ('Внешний аккумулятор HARPER 10000 мАч','https://goo.gl/vkzbJX');
insert into "Gifts" (name, url) values ('Наушники HARPER HB-207 White','https://goo.gl/28ePj3');
insert into "Gifts" (name, url) values ('Записная книжка Classic Red','https://goo.gl/eC2PS9');
insert into "Questions" (question) values ('Она любит путешествовать?');
insert into "Questions" (question) values ('Она - творческая личность?');
insert into "Questions" (question) values ('Ей нравятся головоломки?');
insert into "Questions" (question) values ('Она любит проводить время в компании друзей?');
insert into "Questions" (question) values ('Она играет в компьютерные игры?');
insert into "Questions" (question) values ('Ей нравятся настольные игры?');
insert into "Questions" (question) values ('Она романтичная?');
insert into "Questions" (question) values ('Она следит за своим здоровьем?');
insert into "Questions" (question) values ('Она слушает музыку в транспорте?');
insert into "Questions" (question) values ('Ей нравится рисовать?');
insert into "Questions" (question) values ('Она занимается фитнесом?');
insert into "Questions" (question) values ('Она занимается фотографией?');
insert into "Questions" (question) values ('Ей нравится фотографироваться?');
insert into "Questions" (question) values ('Вы живете вместе?');
insert into "Questions" (question) values ('Вы проводите много времени вместе?');
insert into "Questions" (question) values ('У нее много электронных устройств?');
insert into "Questions" (question) values ('Она - гик?');
insert into "Questions" (question) values ('Она часто слушает музыку?');
insert into "Questions" (question) values ('Она пьет чай/кофе?');
insert into "Questions" (question) values ('Она учится в университете?');
insert into "Questions" (question) values ('Она учится в школе?');
insert into "Questions" (question) values ('Она работает?');
insert into "Questions" (question) values ('Она часто ездит в командировки?');
insert into "Questions" (question) values ('Она любит шумные компании?');
insert into "Questions" (question) values ('Ей нравится проводить время дома?');
insert into "Questions" (question) values ('Она любит готовить?');
insert into "Questions" (question) values ('Она занимается спортом?');
insert into "Questions" (question) values ('Она занимается туризмом?');
insert into "Questions" (question) values ('Она любит мечтать?');
insert into "Questions" (question) values ('Она умная?');
